### PR TITLE
Add store/s3 tests

### PR DESCRIPTION
**Pull request by brunotm**
Replace s3iface.S3API with a minimal interface for s3 which is manageable for testing
Add a minimal s3 mock for testing
Add tests for store/s3

### CODE REVIEW

**Review by rodrigorato — APPROVED** [review]
LGTM.

**Comment by brunotm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- store/s3/s3_test.go  7
- store/s3/s3_mock.go  5
         

Clones added
============
- store/s3/s3_test.go  21
- store/s3/s3_mock.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Unbabel/replicant/pullRequest?prid=4909719&bid=16253882)

**Comment by brunotm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- store/s3/s3_test.go  7
- store/s3/s3_mock.go  5
         

Clones added
============
- store/s3/s3_test.go  21
- store/s3/s3_mock.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Unbabel/replicant/pullRequest?prid=4909719&bid=16253882)

**Comment by brunotm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Complexity increasing per file
==============================
- store/s3/s3_test.go  7
- store/s3/s3_mock.go  5
         

Clones added
============
- store/s3/s3_test.go  21
- store/s3/s3_mock.go  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Unbabel/replicant/pullRequest?prid=4909719&bid=16253882)

**Pull request merged**
